# Generated by Django 4.0.5 on 2022-06-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя:')),
                ('position', models.CharField(max_length=100, verbose_name='Вид деятельности:')),
                ('one_transefer_income', models.IntegerField(verbose_name='стоимость 1 услуги в тнг:')),
                ('any_more_consumption', models.IntegerField(verbose_name='прочие рассходы (обед) в тнг:')),
                ('one_refueling', models.IntegerField(verbose_name='затраты на одну услугу в тнг:')),
                ('one_work_hours', models.IntegerField(verbose_name='время работы за одну услугу:')),
                ('work_graph', models.IntegerField(verbose_name='график работы:')),
                ('services', models.IntegerField(verbose_name='Введите сколько заказов вы сделали сегодня:')),
                ('services_one_day', models.IntegerField(verbose_name='Колличество заказов за день:')),
                ('work_day', models.IntegerField(verbose_name='Колличество рабочих дней в месяце:')),
            ],
        ),
    ]
