# Generated by Django 4.0.5 on 2022-06-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_orders_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ESP',
            field=models.IntegerField(default=2, verbose_name='ЕСП за этот год: '),
            preserve_default=False,
        ),
    ]
