# Generated by Django 4.0.5 on 2022-06-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_esp_orders_order_esp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_ESP',
            field=models.CharField(max_length=100, verbose_name='ЕСП за этот год: '),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_any_more_consumption',
            field=models.CharField(max_length=100, verbose_name='прочие рассходы (обед) в тнг:'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_one_refueling',
            field=models.CharField(max_length=100, verbose_name='затраты на одну услугу в тнг:'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_one_transefer_income',
            field=models.CharField(max_length=100, verbose_name='стоимость 1 услуги в тнг:'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_one_work_hours',
            field=models.CharField(max_length=100, verbose_name='время работы за одну услугу:'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_services',
            field=models.CharField(max_length=100, verbose_name='Введите сколько заказов вы сделали сегодня:'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_services_one_day',
            field=models.CharField(max_length=100, verbose_name='Колличество заказов за день:'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_work_day',
            field=models.CharField(max_length=100, verbose_name='Колличество рабочих дней в месяце:'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_work_graph',
            field=models.CharField(max_length=100, verbose_name='график работы:'),
        ),
    ]
